pipeline {
  agent any
  /*
  agent {
      docker {
          image   "snakee/golang-junit:1.21"
          reuseNode   true
      }
  }
  */

  stages {

    stage('Checkout') {
      steps {
        // Pipeline from SCM: If you set up a Pipeline job and pointed it to a git repo to find the Jenkinsfile, Jenkins performs a "lightweight checkout" to grab the Jenkinsfile first, and then typically a full checkout of the repo, often using the Git Plugin.
        // Implicit Behaviour: Even if you do not explicitly use checkout scm in your stages, the Jenkinsfile-driven job assumes you want the source code available in the workspace.
        // Multibranch Pipelines: When using Multibranch Pipeline jobs, the plugin automatically handles checking out the specific branch/commit that triggered the job.

        // Pulls code from your Git repository
        checkout scm
      }
    }

    stage('Environment Setup') {
      steps {
        sh '''
        echo 'Environment Setup Started'
        # Create and activate a virtual environment
        # python3 - m venv venv
        #.venv / bin / activate
        # Upgrade pip and install dependencies
        # pip install--upgrade pip
        # pip install - r requirements.txt
        echo 'Environment Setup Done'
        '''
      }
    }

    stage('Execute Tests') {

        parallel {
            stage('Unit Tests - Backend') {
            agent {
              docker {
                image 'snakee/golang-junit:1.21'
                reuseNode true
                alwaysPull true
                // args <docker comandline arguments>
              }
            }

            steps {
              dir("bugtracker-backend") {
                sh """
                echo 'Backend Test Execution Started'
                go test / -v. / ...2 > & 1 | go - junit - report > test - results.xml

                # Generate the Coverage Report
                go test - coverprofile = coverage - covermode = atomic. / ...
                  go tool cover - html = coverage.out - o coverage.html
                echo 'Backend Test Execution Completed'

                mkdir - p reports
                mv coverage.html reports /
                """

              }
            }

            post {}

          }

            stage('Unit Tests - Frontend') {
            agent {
              docker {
                image "node:20-alpine"
                reuseNode true
                alwaysPull true
                // args <docker comandline arguments>
              }
            }
            steps {
              dir("bugtracker-frontend") {
                sh """
                echo 'Backend Test Execution Started'
                npm ci
                npm test
                echo 'Backend Test Execution Completed'
                """
              }
            }

            post {}
          }
        }

    }

  }

  // Global post actions
  post {
    always {
      echo 'I will always run, no matter what!'

      junit "bugtracker-frontend/test-results.xml"
      junit "bugtracker-backend/test-results.xml"

      /*
      Jenkins performs three main actions:
      * Analysis: It parses the XML file to count passed, failed, and skipped tests.
      * Visualization: It creates a "Test Result Trend" graph on the job's main page.
      * Build Status: If any tests in that file failed, it automatically marks the build status as Unstable (yellow) instead of Success (green).
      */

      // Publish HTML Report
      publishHTML target: [
        allowMissing: false,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: "bugtracker-backend/reports",
        reportFiles: "coverage.html",
        reportName: "Backend Coverage Report"
      ]

      publishHTML target: [
        allowMissing: false,
        alwaysLinkToLastBuild: true,
        keepAll: true,
        reportDir: "bugtracker-frontend/reports/coverage",
        reportFiles: "index.html",
        reportName: "Frontend Test Execution Report"
      ]


       emailext(
            subject: "Automation Report | ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            mimeType: 'text/html',
            to: 'qa-team@company.com',
            body: """
                <h3>Execution Completed</h3>
                <p>Status: ${currentBuild.currentResult}</p>
                <p>Build URL: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
            """,
            attachmentsPattern: 'bugtracker-backend/backend-results.html,bugtracker-frontend/frontend-results.html',
            attachLog: true
       )


      // Use the [Workspace Cleanup Plugin](https://jenkins.io)
      deleteDir()
    }
    success {
      echo 'Build was successful!'
    }
    failure {
      echo 'Build was failed!'
    }
  }
}